config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #Path to root page
  root to: 'public#index', as: 'root'
  #User handling routes
  devise_for :users, skip: [:sessions, :passwords, :confirmations, :registrations, :unlocks]
  match 'lang/:locale', to: 'visitors#change_locale', as: :change_locale, via: [:get]
  #Update user profile
  #get '/user/edit', to: 'users/users#edit', as: 'user_edit'  
  put '/user/edit', to: 'users#update', as: 'user_update'
  ###############################################################
  devise_scope :user do
    get '/signin', to: 'users/sessions#new', as: 'new_user_session'
    post '/signin', to: 'users/sessions#create', as: 'user_session'
    get '/signout', to: 'users/sessions#sdestroy', as: 'secure_destroy_user_session'
    delete '/signout', to: 'users/sessions#destroy', as: 'destroy_user_session'
    # registrations
    get '/signup', to: 'users/registrations#new', as: 'new_user_registration'
    post '/signup', to: 'users/registrations#create', as: 'user_registration'
    # user accounts
    scope '/account' do
      # confirmation
      get '/verification', to: 'users/confirmations#verification_sent', as: 'user_verification_sent'
      get '/confirm', to: 'users/confirmations#show', as: 'user_confirmation'
      get '/confirm/resend', to: 'users/confirmations#new', as: 'new_user_confirmation'
      post '/confirm', to: 'users/confirmations#create'
      # passwords
      get '/reset-password', to: 'users/passwords#new', as: 'new_user_password'
      get '/reset-password/change', to: 'users/passwords#edit', as: 'edit_user_password'
      put  '/reset-password', to: 'users/passwords#update', as: 'user_password'
      post '/reset-password', to: 'users/passwords#create'
      # unlocks
      post '/unlock', to: 'users/unlocks#create', as: 'user_unlock'
      get '/unlock/new', to: 'users/unlocks#new', as: 'new_user_unlock'
      get '/unlock', to: 'users/unlocks#show'
      # settings & cancellation
      get '/cancel', to: 'users/registrations#cancel', as: 'cancel_user_registration'
      get '/settings', to: 'users/registrations#edit', as: 'edit_user_registration'
      put '/settings', to: 'users/registrations#update', as: 'update_user_registration'
      # account deletion
      delete '/delete', to: 'users/registrations#destroy', as: 'destroy_user_registration'
    end
  end
  #User account paths
  get '/account', to: 'users#account', as: 'account'
  get '/account/edit_news', to: 'users/contents#edit_news'
  put '/account/update_news', to: 'users/contents#update_news'
  ################################################################
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth',
                                  controllers: {
                                      sessions: 'api/v1/devise_token_auth/sessions',
                                      registrations: 'api/v1/devise_token_auth/registrations'
                                  }
      resources :devices, only: [ :create ]
      resources :locations, only: [ :create ]
      post '/analyze', to: 'alpr#analyze', as: 'alpr_analyze'
    end
  end
  #profiles index path
  get '/profiles', to: 'users/profiles#index', as: 'profiles'
  scope :users do
    #User profile new path
    get '/profile/new', to: 'users/profiles#new', as: 'profile_new'
    post '/profile/new', to: 'users/profiles#create', as: 'profile_create'
    #user profile edit & delete path
    resources :profiles, only:[] do
      #User profiles update and destroy paths
      get '/edit', to: 'users/profiles#edit', as: 'edit'
      put '/edit', to: 'users/profiles#update', as: 'update'
      delete '/delete', to: 'users/profiles#destroy', as: 'destroy'
    end
  end

  get '/applied_informatics', to: 'public#info_faculty', as: 'info'
  get '/mathematics', to: 'public#math_faculty', as: 'math'
  get '/physics_informatics', to: 'public#physics_faculty', as: 'physics'
  get '/math_computer_engineering', to: 'public#math_cs_faculty', as: 'math_cs'

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  nilify_blanks
  # Backend validations
  validates :first_name,
            :presence => true
  validates :last_name,
            :presence => true
  validates :patronymic,
            :presence => true
  validates :address,
            :presence => true
  validates :telephone,
            :presence => true
  validates :birth_date,
            :presence => true
  
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApiController
  before_action :authenticate_user!


  #Upgrading user profile and giving driver/business roles
  def upgrade(param)

    if param == "driver"
      @driver = Driver.new(driver_params)
      @driver.user_id = @current_user.id
      respond_to do |format|
        if @driver.save
          format.html { redirect_to account_path, notice: 'driver was successfully created.' }
          format.json { render :show, status: :created, location: @driver }
          @current_user.driver!
        else
          redirect_back_or_default(root_path, :alert => "Something went wrong!.")
        end
      end
    elsif param == "business"
      @business = Business.new(business_params)
      @business.user_id = @current_user.id
      respond_to do |format|
        if @business.save
          format.html { redirect_to business_path, notice: 'business was successfully created.' }
          format.json { render :show, status: :created, location: @business }
          @current_user.business!
        else
          format.html { render :new }
          format.json { render json: @business.errors, status: :unprocessable_entity }
        end
      end
    else
        flash[:notice] = "Bad role!"
    end
  end





  # Only allow a trusted parameter "white list" through.
  def driver_params
    if Rails::VERSION::MAJOR < 4
      params[:driver].permit(:_destroy)
    else
      protected_attrs =  ["created_at", "updated_at"]
      params.require(:driver).permit(Driver.new.attributes.keys - protected_attrs, :_destroy)
    end
  end


  # Only allow a trusted parameter "white list" through.
  def business_params
    if Rails::VERSION::MAJOR < 4
      params[:business].permit(:_destroy)
    else
      protected_attrs =  ["created_at", "updated_at"]
      params.require(:business).permit(Business.new.attributes.keys - protected_attrs, :_destroy)
    end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    self.resource = resource_class.new
  end

  # POST /resource/confirmation
  def create
    self.resource = resource_class.send_confirmation_instructions(resource_params)
    yield resource if block_given?

    if successfully_sent?(resource)
      respond_with({}, location: after_resending_confirmation_instructions_path_for(resource_name))
    else
      respond_with(resource)
    end
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    self.resource = resource_class.confirm_by_token(params[:confirmation_token])
    yield resource if block_given?

    if resource.errors.empty?
      set_flash_message!(:success, :confirmed)
      respond_with_navigational(resource){ redirect_to after_confirmation_path_for(resource_name, resource) }
    else
      respond_with_navigational(resource.errors, status: :unprocessable_entity){ render :new }
    end
  end

  protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    is_navigational_format? ? new_session_path(resource_name) : '/'
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    if signed_in?(resource_name)
      signed_in_root_path(resource)
    else
      new_session_path(resource_name)
    end
  end

  def translation_scope
    'devise.confirmations'
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  prepend_before_action { request.env["devise.skip_timeout"] = true }

  def passthru
    render status: 404, text: "Not found. Authentication passthru."
  end

  def failure
    set_flash_message :danger, :failure, kind: OmniAuth::Utils.camelize(failed_strategy.name), reason: failure_message
    redirect_to after_omniauth_failure_path_for(resource_name)
  end

  protected

  def failed_strategy
    request.respond_to?(:get_header) ? request.get_header("omniauth.error.strategy") : request.env["omniauth.error.strategy"]
  end

  def failure_message
    exception = request.respond_to?(:get_header) ? request.get_header("omniauth.error") : request.env["omniauth.error"]
    error   = exception.error_reason if exception.respond_to?(:error_reason)
    error ||= exception.error        if exception.respond_to?(:error)
    error ||= (request.respond_to?(:get_header) ? request.get_header("omniauth.error.type") : request.env["omniauth.error.type"]).to_s
    error.to_s.humanize if error
  end

  def after_omniauth_failure_path_for(scope)
    new_session_path(scope)
  end

  def translation_scope
    'devise.omniauth_callbacks'
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController

  prepend_before_action :require_no_authentication
  # Render the #edit only if coming from a reset password email link
  append_before_action :assert_reset_token_passed, only: :edit

  # GET /resource/password/new
  def new
    @header_title = t('users.passwords.new.header_title')
    self.resource = resource_class.new
  end

  # POST /resource/password
  def create

    self.resource = resource_class.send_reset_password_instructions(resource_params)
    yield resource if block_given?

    if successfully_sent?(resource)
      respond_with({}, location: after_sending_reset_password_instructions_path_for(resource_name))
    else
      respond_with(resource)
    end
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    @header_title = t('users.passwords.edit.header_title')
    self.resource = resource_class.new
    set_minimum_password_length
    resource.reset_password_token = params[:reset_password_token]
  end

  # PUT /resource/password
  def update
    self.resource = resource_class.reset_password_by_token(resource_params)
    yield resource if block_given?

    if resource.errors.empty?
      resource.unlock_access! if unlockable?(resource)
      if Devise.sign_in_after_reset_password
        flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
        set_flash_message!(:success, flash_message)
        sign_in(resource_name, resource)
      else
        set_flash_message!(:danger, :updated_not_active)
      end
      respond_with resource, location: after_resetting_password_path_for(resource)
    else
      set_minimum_password_length
      respond_with resource
    end
  end

  protected
  def after_resetting_password_path_for(resource)
    Devise.sign_in_after_reset_password ? after_sign_in_path_for(resource) : new_session_path(resource_name)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    new_session_path(resource_name) if is_navigational_format?
  end

  # Check if a reset_password_token is provided in the request
  def assert_reset_token_passed
    if params[:reset_password_token].blank?
      set_flash_message(:danger, :no_token)
      redirect_to new_session_path(resource_name)
    end
  end

  # Check if proper Lockable module methods are present & unlock strategy
  # allows to unlock resource on password reset
  def unlockable?(resource)
    resource.respond_to?(:unlock_access!) &&
        resource.respond_to?(:unlock_strategy_enabled?) &&
        resource.unlock_strategy_enabled?(:email)
  end

  def translation_scope
    'devise.passwords'
  end

  # Helper for use after calling send_*_instructions methods on a resource.
  # If we are in paranoid mode, we always act as if the resource was valid
  # and instructions were sent.
  def successfully_sent?(resource)
    notice = if Devise.paranoid
               resource.errors.clear
               :send_paranoid_instructions
             elsif resource.errors.empty?
               :send_instructions
             end

    if notice
      set_flash_message! :warning, notice
      true
    end
  end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /profiles
  def index
    @profiles = Profile.where(:user_id => current_user.id)
  end

  def new
    @profile = Profile.new
  end

  # GET /profiles/1
  def show
    #render json: @profile
  end

  #Edit /profiles/:id/
  def edit

  end

  # POST /profiles
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = @current_user.id
    @profile.faculty = @current_user.faculty
    if @profile.save
      flash[:notice] = "Портфолио было создано успешно!"
      case @current_user.faculty
        when "P"
          redirect_to info_path
        when "M"
          redirect_to math_path
        when "F"
          redirect_to physics_path
        when "MC"
          redirect_to math_cs_path
      end
    else
      flash[:error] = "При создании Портфолио произошла ошибка. Пожалуйста повторите свои действия!"
      case @current_user.faculty
        when "P"
          redirect_to info_path
        when "M"
          redirect_to math_path
        when "F"
          redirect_to physics_path
        when "MC"
          redirect_to math_cs_path
      end
    end
  end

  # PATCH/PUT /profiles/1
  def update
    if @profile.update(profile_params)
      flash[:notice] = "Ваш Портфолио был успешно обновлен!"
      redirect_back_or_default(root_path)
      #redirect_to request_user_show_path(@request)
    else
      flash[:error] = "Возникли ошибки при обновлении!"
      redirect_back_or_default(root_path, :alert => "Some thing wrong!.")
    end
  end

  # DELETE /profiles/1
  def destroy
    @profile.destroy
    redirect_to profiles_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_profile
    @profile = Profile.find(params[:profile_id])
  end

  # Only allow a trusted parameter "white list" through.
  def profile_params
    if Rails::VERSION::MAJOR < 4
      params[:profile].permit(:_destroy)
    else
      protected_attrs =  ["created_at", "updated_at"]
      params.require(:profile).permit(Profile.new.attributes.keys - protected_attrs, :_destroy)
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  prepend_before_action :require_no_authentication, only: [ :new, :create ]
  prepend_before_action :allow_params_authentication!, only: :create
  prepend_before_action :verify_signed_out_user, only: :destroy
  skip_before_action :set_current_user, except: [:new]
  before_action :require_login

  #prepend_before_action only: [ :create, :destroy ] { request.env["devise.skip_timeout"] = true }

  # GET /resource/sign_in
  def new
    #@header_title = t('users.sessions.header_title')
    self.resource = resource_class.new(sign_in_params)
    clean_up_passwords(resource)
    respond_with(resource, serialize_options(resource))
  end  # End

  #POST /resource/sign_in
  def create
    @alert_message = "Авторизация прошла успешна!!!"
    auth_options = { :scope => :user}
    self.resource = warden.authenticate!(auth_options)
    unless current_user.username.nil?
      flash[:notice] = @alert_message
    end
    #devise code
    set_flash_message :success,  :signed_in if is_flashing_format?
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end


  #GET /resource/sign out
  def sdestroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message :success, :signed_out if signed_out && is_flashing_format?
    yield if block_given?
    respond_to_on_destroy
  end

  #DELETE /resource/ssign_out
  def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message :success, :signed_out if signed_out && is_flashing_format?
    yield if block_given?
    respond_to_on_destroy
  end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end

  private

  def require_login
    unless current_user
      flash[:error] = "Авторизация не прошла. Пожалуйста проверьте ваш Логин и Пароль!"
      redirect_to root_path
    end
  end
  # Check if there is no signed in user before doing the sign out.
  #
  # If there is no signed in user, it will set the flash message and redirect
  # to the after_sign_out path.
  def verify_signed_out_user
    if all_signed_out?
      set_flash_message :warning, :already_signed_out if is_flashing_format?

      respond_to_on_destroy
    end
  end

  def all_signed_out?
    users = Devise.mappings.keys.map { |s| warden.user(scope: s, run_callbacks: false) }

    users.all?(&:blank?)
  end

  def respond_to_on_destroy
    # We actually need to hardcode this as Rails default responder doesn't
    # support returning empty response on GET request
    respond_to do |format|
      format.all { head :no_content }
      format.any(*navigational_formats) { redirect_to after_sign_out_path_for(resource_name) }
    end
  end


  def after_sign_out_path_for(resource)
    if resource.nil?
      root_url
    else
      root_url
    end
  end

end

app/views/users/profiles/_form.html.erb
<div class="row">
  <div class="col-sm">

    <%= f.label "Имя" %>
    <%= f.text_field :first_name, :autofocus => true, :class => 'form-control', :label => false, placeholder: 'Имя' %>

    <%= f.label "Фамилия" %>
    <%= f.text_field :last_name, :autofocus => true, :class => 'form-control', placeholder: 'Фамилия' %>

    <%= f.label "Отчество" %>
    <%= f.text_field :patronymic, :class => 'form-control', placeholder: 'Отчество' %>

    <%= f.label "Дата рождения" %>
    <%= f.input :birth_date, as: :date, html5: true, :label => false, placeholder: 'Укажите дата рождение' %>

    <%= f.label "Телефон" %>
    <%= f.text_field :telephone, :class => 'form-control', :as => "number", placeholder: '79521457878'%>

    <%= f.label "Адрес" %>
    <%= f.text_field :address, :class => 'form-control', placeholder: 'Адрес' %>

    <%= f.label "Биография" %>
    <%= f.input :description, :class => 'form-control', :label => false, placeholder: 'Напишите кратко о себе' %>

    <%= f.label "Пол" %>
    <%= f.select :gender, [['Мужской', 'M'], ['Женский', 'F']], {include_blank: 'Выбрать пол'}, { :class => 'form-control', :"data-fv-field"=> "user[gender]",:"data-fv-notempty"=>"true", :"data-fv-notempty-message"=>"Select a gender",  } %>
  </div>
  <div class="col-sm">

    <%= f.label "Место учебы" %>
    <%= f.input :study_place, :class => 'form-control', :label => false, placeholder: 'Введите название ВУЗа' %>
    <%= f.label "Учебный год" %>
    <%= f.input :course_year, :class => 'form-control', :label => false, placeholder: 'Введите ваш учебный год' %>
    <%= f.label "Ссылка на портфолио" %>
    <%= f.input :portfolio_url, :class => 'form-control', :label => false, placeholder: 'Введите ссылку на ваш портфолио' %>

    <div id="accordion">
      <p>
        <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Каръера
        </button>
        <button class="btn btn-primary collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Навыки
        </button>
        <button class="btn btn-primary collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Контакты
        </button>
        <button class="btn btn-primary collapsed" type="button" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          Достижения
        </button>
      </p>

      <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
        <div class="card-body modal-full">
          <%= f.label "Настоящая должность" %>
          <%= f.input :first_position, :class => 'form-control', :label => false, placeholder: 'Укажите настоящую должность' %>


          <%= f.label "Настоящее место работы" %>
          <%= f.input :first_workplace, :class => 'form-control', :label => false, placeholder: 'Укажите настоящее место работы' %>


          <%= f.label "Период работы" %>
          <%= f.input :work_date, :class => 'form-control', :label => false, placeholder: '05.04.2012-Сейчас' %>

          <%= f.label "Предыдущая должность" %>
          <%= f.input :second_position, :class => 'form-control', :label => false, placeholder: 'Укажите предыдущую должность' %>


          <%= f.label "Предыдущее место работы" %>
          <%= f.input :second_workplace, :class => 'form-control', :label => false, placeholder: 'Укажите предыдущее место работы' %>


          <%= f.label "Период работы" %>
          <%= f.input :old_work_date, :class => 'form-control', :label => false, placeholder: '05.04.2012-10.12.2015' %>

          <%= f.label "Предыдущая должность" %>
          <%= f.input :third_position, :class => 'form-control', :label => false, placeholder: 'Укажите предыдущую должность' %>


          <%= f.label "Предыдущий место работы" %>
          <%= f.input :third_workplace, :class => 'form-control', :label => false, placeholder: 'Укажите предыдущий место работы' %>


          <%= f.label "Период работы" %>
          <%= f.input :last_work_date, :class => 'form-control', :label => false, placeholder: '05.04.2012-10.12.2015' %>          </div>
      </div>
      <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
        <div class="card-body modal-full">
          <%= f.label "Технические навыки" %>
          <%= f.input :technical_skills, :class => 'form-control', :label => false, placeholder: 'Программирование, Дизайн....' %>
          <%= f.label "Культурные навыки" %>
          <%= f.input :cultural_skills, :class => 'form-control', :label => false, placeholder: 'Полиглот, Историк....' %>
          <%= f.label "Научные навыки" %>
          <%= f.input :scientific_skills, :class => 'form-control', :label => false, placeholder: 'Писать научные статъти, Проведение исследований....' %>
          <%= f.label "Общие навыки" %>
          <%= f.input :general_skills, :class => 'form-control', :label => false, placeholder: 'Переговоры, Общительность....' %>
        </div>
      </div>
      <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
        <div class="card-body modal-full">
          <%= f.label "Вконтакте" %>
          <%= f.input :vk, :class => 'form-control', :label => false, placeholder: 'Введите ссылку на ваш учетный запись' %>
          <%= f.label "Facebook" %>
          <%= f.input :facebook, :class => 'form-control', :label => false, placeholder: 'Введите ссылку на ваш учетный запись' %>
          <%= f.label "Instagram" %>
          <%= f.input :instagram, :class => 'form-control', :label => false, placeholder: 'Введите ссылку на ваш учетный запись' %>
        </div>
      </div>
      <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordion">
        <div class="card-body modal-full">
          <%= f.label "Достижения" %>
          <%= f.input :achievements, :class => 'form-control', :label => false, placeholder: 'Напишите про своих достижений' %>
          <%= f.input :achievement_docs, :as => :hidden, :class => 'form-control', :label => false %>

          <label>Документы подтверждающие достижения</label>
          <div class="col-md-12 form-group" style="margin-top: 20px">

            <span class="btn btn-success fileinput-button" style="margin-left: 25%; margin-top: 20px;">
                <span>Загрузить</span>
              <%= f.file_field :workplace, accept: 'image/*', multipart: true, multiple: true,
                               data: { 'resource-name' => 'image' }, :style => '', :input_html => { :multiple => true } %>
            </span>
          </div>




        </div>
      </div>

    </div>

    <%= f.label "Интересы" %>
    <%= f.input :hobbies, :class => 'form-control', :label => false, placeholder: 'Напишите про своих достижений' %>

  </div>
  <div class="col-sm">
    <div class="col-md-12 form-group" style="margin-top: 20px">
        <h6 class="m-t-2 " style="margin-left: 18%" >
          <%= t("users.account.upload-profile-image") %>
        </h6>
        <div class="fileinput-image">
          <% if profile.image_url.nil? %>
            <img src="<%= image_path ("user-placeholder")%>" class="m-x-auto img-fluid img-circle" alt="avatar">
          <%else%>
            <img src="<%= profile.image_url %>" alt="avatar" width="300" height="300">
          <% end %>
        </div>
        <span class="btn btn-success fileinput-button" style="margin-left: 25%; margin-top: 20px;">
                <!-- Change based on action -->
          <% if profile.image_url.nil? %>
                    <span><%= t("users.account.upload-image") %></span>
                <% else %>
                    <span><%= t("users.account.change-image") %></span>
                <% end %>
          <%= f.file_field :image_url, accept: '*',
                           data: { 'resource-name' => 'image'}, :style => '' %>
        </span>
    </div>

  </div>
</div>



    
    

app/views/users/profiles/_new.html.erb
<!-- Page Content -->
<% unless profile.nil? %>
<div class="modal modal-full" id="portfolioModalCenter"  tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered  modal-full" role="document" style="height: 100%">
    <div class="modal-content modal-full" style="height: 100%">
      <div class="modal-header">
        <h5 class="modal-title text-center" id="exampleModalCenterTitle" >Создать Портфолио</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"></span>
        </button>
      </div>
      <div class="modal-body " style="height: 100%">
        <%= simple_form_for(profile, :url => profile_new_path(profile),
                            :html => { :class => 'directFileUpload',
                                       :role => 'form'}) do |f| %>
          <%= render 'users/profiles/form', f: f, profile: profile %>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрить</button>
            <%= f.submit  "Создать", :class => 'btn btn-primary '  %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/profiles/edit.html.erb
<!-- Page Content -->
<div class="container fluid">
  <div class="card border-0 shadow my-5">
    <div class="card-body">
      <h1 class="text-center form-title"><%= t("users.vehicles.edit.title") %></h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/profiles/index.html.erb
<!-- Page Content -->
<div class="container fluid">
  <div class="card border-0 shadow my-5">
    <div class="card-body">
      <h2 class="text-center" style="margin-top: 20px; margin-bottom: 20px;"><%= t("global.list") %></h2>
      <table class="table">
        <thead class="thead-dark" >
        <tr>
          <th scope="col"><%= t("global.name") %></th>
          <th scope="col"><%= t("global.description") %></th>
          <th scope="col"><%= t("users.profiles.form.price") %></th>
          <th scope="col"><%= t("users.profiles.form.quantity") %></th>
          <th scope="col"><%= t("global.delete") %>/<%= t("global.edit") %></th>
        </tr>
        </thead>
        <tbody>
        <% @profiles.each do |profile|%>
          <tr>
            <td><%= profile.name%></td>
            <td><%= profile.description%></td>
            <td><%= profile.price%></td>
            <td><%= profile.quantity%></td>
            <td><%= link_to t("global.delete"), profile_destroy_path(profile),:method => :delete %>/<%= link_to t("global.edit"), profile_edit_path(profile) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <div class="d-flex justify-content-center" style="margin-bottom: 40px;">
        <%= link_to t("global.create"), profile_new_path, :class => 'btn btn-primary '%>
      </div>
    </div>
  </div>
</div>