config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #Path to root page
  root to: 'public#index', as: 'root'
  #User handling routes
  devise_for :users, skip: [:sessions, :passwords, :confirmations, :registrations, :unlocks]
  match 'lang/:locale', to: 'visitors#change_locale', as: :change_locale, via: [:get]
  #Update user profile
  #get '/user/edit', to: 'users/users#edit', as: 'user_edit'  
  put '/user/edit', to: 'users#update', as: 'user_update'
  ###############################################################
  devise_scope :user do
    get '/signin', to: 'users/sessions#new', as: 'new_user_session'
    post '/signin', to: 'users/sessions#create', as: 'user_session'
    get '/signout', to: 'users/sessions#sdestroy', as: 'secure_destroy_user_session'
    delete '/signout', to: 'users/sessions#destroy', as: 'destroy_user_session'
    # registrations
    get '/signup', to: 'users/registrations#new', as: 'new_user_registration'
    post '/signup', to: 'users/registrations#create', as: 'user_registration'
    # user accounts
    scope '/account' do
      # confirmation
      get '/verification', to: 'users/confirmations#verification_sent', as: 'user_verification_sent'
      get '/confirm', to: 'users/confirmations#show', as: 'user_confirmation'
      get '/confirm/resend', to: 'users/confirmations#new', as: 'new_user_confirmation'
      post '/confirm', to: 'users/confirmations#create'
      # passwords
      get '/reset-password', to: 'users/passwords#new', as: 'new_user_password'
      get '/reset-password/change', to: 'users/passwords#edit', as: 'edit_user_password'
      put  '/reset-password', to: 'users/passwords#update', as: 'user_password'
      post '/reset-password', to: 'users/passwords#create'
      # unlocks
      post '/unlock', to: 'users/unlocks#create', as: 'user_unlock'
      get '/unlock/new', to: 'users/unlocks#new', as: 'new_user_unlock'
      get '/unlock', to: 'users/unlocks#show'
      # settings & cancellation
      get '/cancel', to: 'users/registrations#cancel', as: 'cancel_user_registration'
      get '/settings', to: 'users/registrations#edit', as: 'edit_user_registration'
      put '/settings', to: 'users/registrations#update', as: 'update_user_registration'
      # account deletion
      delete '/delete', to: 'users/registrations#destroy', as: 'destroy_user_registration'
    end
  end
  #User account paths
  get '/account', to: 'users#account', as: 'account'
  get '/account/edit_news', to: 'users/contents#edit_news'
  put '/account/update_news', to: 'users/contents#update_news'
  ################################################################
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth',
                                  controllers: {
                                      sessions: 'api/v1/devise_token_auth/sessions',
                                      registrations: 'api/v1/devise_token_auth/registrations'
                                  }
      resources :devices, only: [ :create ]
      resources :locations, only: [ :create ]
      post '/analyze', to: 'alpr#analyze', as: 'alpr_analyze'
    end
  end
  #profiles index path
  get '/profiles', to: 'users/profiles#index', as: 'profiles'
  scope :users do
    #User profile new path
    get '/profile/new', to: 'users/profiles#new', as: 'profile_new'
    post '/profile/new', to: 'users/profiles#create', as: 'profile_create'
    #user profile edit & delete path
    resources :profiles, only:[] do
      #User profiles update and destroy paths
      get '/edit', to: 'users/profiles#edit', as: 'edit'
      put '/edit', to: 'users/profiles#update', as: 'update'
      delete '/delete', to: 'users/profiles#destroy', as: 'destroy'
    end
  end

  get '/applied_informatics', to: 'public#info_faculty', as: 'info'
  get '/mathematics', to: 'public#math_faculty', as: 'math'
  get '/physics_informatics', to: 'public#physics_faculty', as: 'physics'
  get '/math_computer_engineering', to: 'public#math_cs_faculty', as: 'math_cs'

end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :user
  has_many :location
end

app/controllers/api/v1/devices_controller.rb
class Api::V1::DevicesController < ApiController

  # PATCH/PUT /devices/:device
  def create
    @user = current_user
    @device = Device.find_or_create_by(:user_id => @user.id, :udid => device_params[:udid])

    if @device.update(device_params)

      render json: {
                 status: 200,
                 message: "Response successfully sent!",
                 params: device_params
             }.to_json
    else
      render json: {
                 status: 400,
                 message: "User device params failed to save!",
                 error: @device.errors
             }.to_json
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
  def device_params
    if Rails::VERSION::MAJOR < 4
      #In here should be given object name
      params[:device].permit(:_destroy)
    else
      params.require(:device).permit(:installationId, :expoVersion, :appOwnership, :systemName, :systemVersion, :deviceName, :deviceYearClass, :sessionId, :isDevice, :platform, :udid)
    end
  end
end

app/views/devices/_form.html.erb
<%= form_with(model: device, local: true) do |form| %>
  <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :speed %>
    <%= form.text_field :speed %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :accuracy %>
    <%= form.text_field :accuracy %>
  </div>

  <div class="field">
    <%= form.label :heading %>
    <%= form.text_field :heading %>
  </div>

  <div class="field">
    <%= form.label :altitude %>
    <%= form.text_field :altitude %>
  </div>

  <div class="field">
    <%= form.label :altitudeAccuracy %>
    <%= form.text_field :altitudeAccuracy %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<div class="container fluid">
  <div class="card border-0 shadow my-5">
    <div class="card-body">

      <h1>Editing Device</h1>

      <%= render 'form', device: @device %>

      <%= link_to 'Show', @device %> |
      <%= link_to 'Back', devices_path %>

    </div>
  </div>
</div>

app/views/devices/index.html.erb
<div class="container fluid">
  <div class="card border-0 shadow my-5">
    <div class="card-body">

      <p id="notice"><%= notice %></p>

      <h1>Devices</h1>

      <table>
        <thead>
          <tr>
            <th>Speed</th>
            <th>Longitude</th>
            <th>Latitude</th>
            <th>Accuracy</th>
            <th>Heading</th>
            <th>Altitude</th>
            <th>Altitudeaccuracy</th>
            <th>User</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @devices.each do |device| %>
            <tr>
              <td><%= device.speed %></td>
              <td><%= device.longitude %></td>
              <td><%= device.latitude %></td>
              <td><%= device.accuracy %></td>
              <td><%= device.heading %></td>
              <td><%= device.altitude %></td>
              <td><%= device.altitudeAccuracy %></td>
              <td><%= device.user %></td>
              <td><%= link_to 'Show', device %></td>
              <td><%= link_to 'Edit', edit_device_path(device) %></td>
              <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Device', new_device_path %>

    </div>
  </div>
</div>

app/views/devices/new.html.erb
<!-- Page Content -->
<div class="container fluid">
  <div class="card border-0 shadow my-5">
    <div class="card-body">

        <h1>New Device</h1>

        <%= render 'form', device: @device %>

        <%= link_to 'Back', devices_path %>

    </div>
  </div>
</div>

app/views/devices/show.html.erb
<!-- Page Content -->
<div class="container fluid">
  <div class="card border-0 shadow my-5">
    <div class="card-body">

      <p id="notice"><%= notice %></p>

      <p>
        <strong>Speed:</strong>
        <%= @device.speed %>
      </p>

      <p>
        <strong>Longitude:</strong>
        <%= @device.longitude %>
      </p>

      <p>
        <strong>Latitude:</strong>
        <%= @device.latitude %>
      </p>

      <p>
        <strong>Accuracy:</strong>
        <%= @device.accuracy %>
      </p>

      <p>
        <strong>Heading:</strong>
        <%= @device.heading %>
      </p>

      <p>
        <strong>Altitude:</strong>
        <%= @device.altitude %>
      </p>

      <p>
        <strong>Altitudeaccuracy:</strong>
        <%= @device.altitudeAccuracy %>
      </p>

      <p>
        <strong>User:</strong>
        <%= @device.user %>
      </p>

      <%= link_to 'Edit', edit_device_path(@device) %> |
      <%= link_to 'Back', devices_path %>

    </div>
  </div>
</div>