config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #Path to root page
  root to: 'public#index', as: 'root'
  #User handling routes
  devise_for :users, skip: [:sessions, :passwords, :confirmations, :registrations, :unlocks]
  match 'lang/:locale', to: 'visitors#change_locale', as: :change_locale, via: [:get]
  #Update user profile
  #get '/user/edit', to: 'users/users#edit', as: 'user_edit'  
  put '/user/edit', to: 'users#update', as: 'user_update'
  ###############################################################
  devise_scope :user do
    get '/signin', to: 'users/sessions#new', as: 'new_user_session'
    post '/signin', to: 'users/sessions#create', as: 'user_session'
    get '/signout', to: 'users/sessions#sdestroy', as: 'secure_destroy_user_session'
    delete '/signout', to: 'users/sessions#destroy', as: 'destroy_user_session'
    # registrations
    get '/signup', to: 'users/registrations#new', as: 'new_user_registration'
    post '/signup', to: 'users/registrations#create', as: 'user_registration'
    # user accounts
    scope '/account' do
      # confirmation
      get '/verification', to: 'users/confirmations#verification_sent', as: 'user_verification_sent'
      get '/confirm', to: 'users/confirmations#show', as: 'user_confirmation'
      get '/confirm/resend', to: 'users/confirmations#new', as: 'new_user_confirmation'
      post '/confirm', to: 'users/confirmations#create'
      # passwords
      get '/reset-password', to: 'users/passwords#new', as: 'new_user_password'
      get '/reset-password/change', to: 'users/passwords#edit', as: 'edit_user_password'
      put  '/reset-password', to: 'users/passwords#update', as: 'user_password'
      post '/reset-password', to: 'users/passwords#create'
      # unlocks
      post '/unlock', to: 'users/unlocks#create', as: 'user_unlock'
      get '/unlock/new', to: 'users/unlocks#new', as: 'new_user_unlock'
      get '/unlock', to: 'users/unlocks#show'
      # settings & cancellation
      get '/cancel', to: 'users/registrations#cancel', as: 'cancel_user_registration'
      get '/settings', to: 'users/registrations#edit', as: 'edit_user_registration'
      put '/settings', to: 'users/registrations#update', as: 'update_user_registration'
      # account deletion
      delete '/delete', to: 'users/registrations#destroy', as: 'destroy_user_registration'
    end
  end
  #User account paths
  get '/account', to: 'users#account', as: 'account'
  get '/account/edit_news', to: 'users/contents#edit_news'
  put '/account/update_news', to: 'users/contents#update_news'
  ################################################################
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth',
                                  controllers: {
                                      sessions: 'api/v1/devise_token_auth/sessions',
                                      registrations: 'api/v1/devise_token_auth/registrations'
                                  }
      resources :devices, only: [ :create ]
      resources :locations, only: [ :create ]
      post '/analyze', to: 'alpr#analyze', as: 'alpr_analyze'
    end
  end
  #profiles index path
  get '/profiles', to: 'users/profiles#index', as: 'profiles'
  scope :users do
    #User profile new path
    get '/profile/new', to: 'users/profiles#new', as: 'profile_new'
    post '/profile/new', to: 'users/profiles#create', as: 'profile_create'
    #user profile edit & delete path
    resources :profiles, only:[] do
      #User profiles update and destroy paths
      get '/edit', to: 'users/profiles#edit', as: 'edit'
      put '/edit', to: 'users/profiles#update', as: 'update'
      delete '/delete', to: 'users/profiles#destroy', as: 'destroy'
    end
  end

  get '/applied_informatics', to: 'public#info_faculty', as: 'info'
  get '/mathematics', to: 'public#math_faculty', as: 'math'
  get '/physics_informatics', to: 'public#physics_faculty', as: 'physics'
  get '/math_computer_engineering', to: 'public#math_cs_faculty', as: 'math_cs'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <!--<div class="container_style">-->
  <div class="container ">
    <div class="row">
      <div class="col-lg-6">
        <ul class="copyright">
          <li class="footer_psk">Псковский Государственный университет</li>
          <li class="footer_li">
            <i class="fas fa-globe-americas"></i>
            180000, Псков, пл. Ленина, дом 2.
          </li>
          <li class="footer_li">
            <i class="fas fa-phone-square"></i>
            Телефон: +7(8112) 29-70-01, Факс:+7(8112) 29-70-02
          </li>
          <li class="footer_li">
            <i class="fas fa-envelope"></i>
            Электронная почта: <a href="mail.ru/message">rector@pskgu.ru</a>
          </li>
        </ul>
      </div>
      <div class="col-lg-6">
        <ul class="copyright lef">
          <li class="footer_psk">Физико-математический факультет</li>
          <li class="footer_li">
            <i class="fas fa-globe-americas"></i>
            180000, Псков, пл. Ленина, дом 2.
            кабинет 102 (4 этаж)
          </li>
          <li class="footer_li">
            <i class="fas fa-phone-square"></i>
            Телефон: +7 (8112) 29-70-86
          </li>
          <li class="footer_li">
            <i class="fas fa-envelope"></i>
            Электронная почта: <a href="mail.ru/message"> fmf.pskgu.ru</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <!--</div>-->
</footer>

app/views/layouts/_languages_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="langModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title">Languages</h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"></span>
        </button>
      </div>
      <div class="modal-body" style="padding: 0 !important;">
        <ul class="langList">
          <% I18n.available_locales.each do |lang| %>
            <li>
              <%= link_to t(lang), change_locale_path(lang) %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
  <!--<div class="container_style">-->
  <div class="container">
    <div class="row">
      <div class="col-lg-3">
        <div class="user">
          <div class="user_avatar">
            <a href="<%= root_path %>"><img src="<%= image_path('Pskovgu.png') %>" class="user__avatar_img" alt="logo"></a>
          </div>
        </div>
      </div>
      <div class="col-lg-3 ">
        <div class="user_name">
          Физико-математический факультет
        </div>
      </div>
      <div class="col-lg-6">
        <div class="registr">
          <ul class="nav float-right">
            <% if @current_user.user? %>
              <li class="nav-item">
                <a class="nav-link nav_hover" href="<%= account_path %>" >Личный кабинет</a>
              </li>
              <li class="nav-item">
                <a class="nav-link nav_hover" href="<%= destroy_user_session_path %>">Выйти</a>
              </li>
              <% if @current_user.admin?%>
                <li class="nav-item">
                  <a class="nav-link nav_hover" href="<%= rails_admin_path %>">Админ</a>
                </li>
              <% end %>
            <% else %>
              <li class="nav-item">
                <a class="nav-link nav_hover" href="#" data-toggle="modal" data-target="#exampleModal">Войти</a>
              </li>
              <li class="nav-item">
                <a class="nav-link nav_hover" href="#" data-toggle="modal" data-target="#exampleModalCenter">Регистрация</a>
              </li>
              <li class="nav-item">
                <a class="nav-link nav_hover" href="#" data-toggle="modal" data-target="#langModal"><%= t("layouts.navigation.language")%></a>
              </li>
            <% end %>

          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- </div> -->

app/views/layouts/_portfolio_show.html.erb
<% unless profile.achievement_docs.nil?%>
  <% @images = JSON.parse profile.achievement_docs %>
<% end %>
<div class="modal fade " id="portfolioModalCenter<%= profile.id%>"  tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" >
  <div class="modal-dialog modal-full"  role="document" style="height: 100%">
    <div class="modal-content modal-full" style="padding-bottom: 40px; height: 100%">
      <div class="modal-header" style="border-bottom: none">
        <h5 class="modal-title" id="exampleModalCenterTitle" style="margin-left: 10%"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color: #fff;">

        </button>
      </div>
      <div class="row" style="margin-left: 10%">
        <div class="col-lg-4">
          <% if profile.image_url.nil? %>
            <img src="<%= image_path('user-placeholder.jpg') %>" style='width:100%;' alt="" class="img_person rounded" width="500" height="500" >
          <% else %>
            <img src="<%= profile.image_url %>" alt="" class="img_person rounded" width="500" height="500">
          <% end %>
          <figcaption style="width:300px; text-align: center;  color:dodgerblue; font-weight: bold;"><%= profile.first_name %> <%= profile.last_name %> <%= profile.patronymic %></figcaption>
        </div>
        <div class="col-lg-8" style="margin-left: -80px;">
          <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
            <li class="nav-item ">
              <a class="nav-link active " id="pills-home-tab<%= profile.id %>" data-toggle="pill" href="#pills-home<%= profile.id %>" role="tab" aria-controls="pills-home" aria-selected="true" style="color: #53ff1a">О Пользователе</a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" id="pills-education-tab<%= profile.id %>" data-toggle="pill" href="#pills-education<%= profile.id %>" role="tab" aria-controls="pills-profile" aria-selected="false" style="color: #53ff1a">Образования</a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" id="pills-profile-tab<%= profile.id %>" data-toggle="pill" href="#pills-profile<%= profile.id %>" role="tab" aria-controls="pills-profile" aria-selected="false" style="color: #53ff1a">Карьера</a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" id="pills-contact-tab<%= profile.id %>" data-toggle="pill" href="#pills-contact<%= profile.id %>" role="tab" aria-controls="pills-contact" aria-selected="false" style="color: #53ff1a">Контакты</a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" id="pills-hobby-tab<%= profile.id %>" data-toggle="pill" href="#pills-hobby<%= profile.id %>" role="tab" aria-controls="pills-hobby" aria-selected="false" style="color: #53ff1a">Интересы</a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" id="pills-navik-tab<%= profile.id %>" data-toggle="pill" href="#pills-navik<%= profile.id %>" role="tab" aria-controls="pills-navik" aria-selected="false" style="color: #53ff1a">Навыки</a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" id="pills-dostig-tab<%= profile.id %>" data-toggle="pill" href="#pills-dostig<%= profile.id %>" role="tab" aria-controls="pills-dostig" aria-selected="false" style="color: #53ff1a">Достижения</a>
            </li>
          </ul>
          <div class="tab-content" id="pills-tabContent">
            <div class="tab-pane fade show active" id="pills-home<%= profile.id %>" role="tabpanel" aria-labelledby="pills-home-tab">
              <ul class="ul_ul">
                <li class="li_li">Имя: <%= profile.first_name %></li>
                <li class="li_li">Отчество: <%= profile.patronymic %></li>
                <li class="li_li">Фамилия: <%= profile.last_name %></li>
                <li class="li_li">Пол: <%= profile.gender %></li>
                <li class="li_li">Дата-рождения: <%= profile.birth_date.strftime("%d.%m.%Y") %></li>
                <li class="li_li">Адрес: <%= profile.address %></li>

              </ul>
              <div class="about_yourself">
                <div class="about_yourself_span">
                  <span>Немного о себе</span>
                </div>
                <div class="about_yourself_text">
                  <p><%= profile.description %></p>
                </div>
              </div>
            </div>
            <div class="tab-pane fade" id="pills-profile<%= profile.id %>" role="tabpanel" aria-labelledby="pills-profile-tab">
              <div class="accordion" id="accordionExample">
                <div class="card">
                  <div class="card-header" id="headingOne">
                    <h5 class="mb-0">
                      <button class="btn btn-link badge badge-pill badge-primary" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        должность настоящего время  #1
                      </button>
                    </h5>
                  </div>

                  <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                    <div class="card-body">
                      <ul class="ul_ul" style="color: #333333;">
                        <li class="li_li">Должность: <%= profile.first_position %></li>
                        <li class="li_li">Огранизация: <%= profile.first_workplace %></li>
                        <li class="li_li">Годы: <%= profile.work_date %></li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="card">
                  <div class="card-header" id="headingTwo">
                    <h5 class="mb-0">
                      <button class="btn btn-link collapsed badge badge-pill badge-primary" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        предудущый должность#2
                      </button>
                    </h5>
                  </div>
                  <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                    <div class="card-body">
                      <ul class="ul_ul" style="color: #333333">
                        <li class="li_li">Должность: <%= profile.second_position %></li>
                        <li class="li_li">Огранизация: <%= profile.second_workplace %></li>
                        <li class="li_li">Годы: <%= profile.old_work_date %></li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="card">
                  <div class="card-header" id="headingThree">
                    <h5 class="mb-0">
                      <button class="btn btn-link collapsed badge badge-pill badge-primary" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                        предудущий должность #3
                      </button>
                    </h5>
                  </div>
                  <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                    <div class="card-body">
                      <ul class="ul_ul" style="color: #333333">
                        <li class="li_li">Должность: <%= profile.third_position %></li>
                        <li class="li_li">Огранизация: <%= profile.third_workplace %></li>
                        <li class="li_li">Годы: <%= profile.last_work_date %></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="tab-pane fade" id="pills-contact<%= profile.id %>" role="tabpanel" aria-labelledby="pills-contact-tab">
              <ul class="ul_ul">
                <li class="li_li">Телефон: <%= profile.telephone%></li>
                <li class="li_li">Почта: <%= profile.user.email %></li>
                <li class="li_li">VК: <%= profile.vk %></li>
                <li class="li_li">Facebook: <%= profile.facebook %></li>
                <li class="li_li">Instagram: <%= profile.instagram %></li>
              </ul>
            </div>
            <div class="tab-pane fade" id="pills-hobby<%= profile.id %>" role="tabpanel" aria-labelledby="pills-hobby-tab">
              <ul class="ul_ul">
                <% unless profile.hobbies.nil?%>
                  <% profile.hobbies.split(",").each do |hobby|%>
                    <li class="li_li"><%= hobby %></li>
                  <% end %>
                <% end %>
              </ul>
            </div>
            <div class="tab-pane fade" id="pills-navik<%= profile.id %>" role="tabpanel" aria-labelledby="pills-navik-tab">
              <div class="row">
                <div class="col-3">
                  <div class="list-group" id="list-tab" role="tablist">
                    <a class="navk active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">Технические </a>
                    <a class="navk" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">Культурные </a>
                    <a class="navk" id="list-messages-list" data-toggle="list" href="#list-messages" role="tab" aria-controls="messages">Научные</a>
                    <a class="navk" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings">Общие</a>
                  </div>
                </div>
                <div class="col-9">
                  <div class="tab-content" id="nav-tabContent">
                    <div class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list">
                      <ul class="ul_ul">
                        <li class="li_li"><%= profile.technical_skills%></li>
                        <li class="li_li"><%= profile.cultural_skills%></li>
                        <li class="li_li"><%= profile.scientific_skills%></li>
                        <li class="li_li"><%= profile.general_skills%></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="tab-pane fade" id="pills-dostig<%= profile.id %>" role="tabpanel" aria-labelledby="pills-dostig-tab">
              <div class="row">
                <% unless profile.achievement_docs.nil?%>
                  <% @images.each do |image|%>
                  <div class="col-lg-4" style="float: left;">
                    <div class="card">

                        <img src="<%= image %>" class="card-img-top" alt="..." height="200" style="float: left;">

                      <div class="card-footer">
                        <small class="text-muted" style="font-weight: bold; color: #fff;"><%= profile.achievements %></small>
                      </div>
                    </div>

                  </div>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class="tab-pane fade" id="pills-education<%= profile.id %>" role="tabpanel" aria-labelledby="pills-home-tab">
              <ul>
                <li class="li_li">Напрваление:
                  <% case profile.faculty %>
                  <% when "M" %>
                    Математика
                  <% when "P" %>
                    Прикладная информатика
                  <% when "MC" %>
                    Математика и компютерные науки
                  <% when "F" %>
                    Физика и информатика
                  <% end %>
                </li>
                <li class="li_li">Место учебы: <%= profile.study_place %></li>
                <li class="li_li">Учебный год: <%= profile.course_year %></li>
                <li class="li_li">Ссылка на портфолио: <%= profile.portfolio_url %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div> <!-- .modal-content -->
</div>

app/views/layouts/_side_navigation.html.erb
<aside class="sidebar">
  <nav class="nav scroll">
    <ul class="nav__list">
      <li class="nav__item nav__item_active">
        <a href="<%= root_path %>" class="nav__link">
          <i class="fak fas fa-home" aria-hidden="true"></i><span class="nav__text">Главная</span>
        </a>
      </li>
      <li class="nav__item nav__item_active">
        <a href="<%= info_path %>" class="nav__link">
          <i class="fak fas fa-laptop" aria-hidden="true"></i><span class="nav__text">Прикладная информатика</span>
        </a>
      </li>
      <li class="nav__item nav__item_active">
        <a href="<%= math_path %>" class="nav__link">
          <i class="fak fas fa-infinity" aria-hidden="true"></i><span class="nav__text">Математика</span>
        </a>
      </li>
      <li class="nav__item nav__item_active">
        <a href="<%= physics_path %>" class="nav__link">
          <i class="fak fas fa-atom" aria-hidden="true"></i><span class="nav__text">Физика-Информатика</span>
        </a>
      </li>
      <li class="nav__item nav__item_active">
        <a href="<%= math_cs_path %>" class="nav__link">
          <i class="fak fas fa-code" aria-hidden="true"></i><span class="nav__text">Математика и компютерные науки</span>
        </a>
      </li>
      <!--<li class="nav__item nav__item_active">-->
      <!--<a href="#" class="nav__link">-->
      <!--<i class="fa fas fa-brain" aria-hidden="true"></i><span class="nav__text">Информатика и вычислительная техника</span>-->
      <!--</a>-->
      <!--</li>-->
    </ul>
  </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
  <head>
    <meta charset="utf-8" />
    <meta name="author" content="Master Rails" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%# Application CSS & JS and all includes %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%# Meta Data %>
    <%= csrf_meta_tags %>
    <title><%= content_for?(:title) ? yield(:title) : "Прикладная информатика" %></title>
  </head>
  <body class="stretched sticky-responsive-menu">
  <div class="wrapper">
    <div class="maincontent">
      <header class="header">
        <%# Main  navigation content %>
        <%= render 'layouts/navigation' %>
      </header>
      <main class="main">
        <!--<div class="container_style"></div> -->
        <div class="container">
    <%# Side  navigation content %>
    <%= render 'layouts/side_navigation' %>
    <%# Languages Modal Popup %>
    <%= render 'layouts/languages_modal' %>
    <% if flash[:notice] %>
      <div class="notice alert alert-success alert-dismissible fade show" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% elsif flash[:error]%>
      <div class="notice alert alert-danger alert-dismissible fade show" role="alert">
        <%= flash[:error] %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <%# Main page content %>
    <%= yield %>
    </div>
      </main>
    </div>
  </div>
  <%# Main footer content %>
  <%= render 'layouts/footer' %>
  <%# Authentication modal %>
  <%= render 'users/sessions/new' %>
  <%# Registration modal %>
  <%= render 'users/registrations/new' %>
  <%# Portfolio modal %>
  <%= render 'users/profiles/new', profile: Profile.new %>
  </body>
</html>